// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Nuke.VisualStudio
{
    static class Vsix
    {
        public const string Id = "Nuke.VisualStudio";
        public const string Name = "NUKE Support";
        public const string Description = @"Task Runner integration for execution of targets and code snippets for authoring";
        public const string Language = "en-US";
        public const string Version = "0.1.0";
        public const string Author = "NUKE";
        public const string Tags = "nuke, build, automation";
    }
}
